server.port: 10737

app:
  telegram:
    token: some-token
    bot-username: some-username

spring:
  h2:
    console:
      enabled: true
  datasource:
    #    url: jdbc:h2:file:./botdb;MODE=PostgreSQL
    url: jdbc:h2:mem:botdb;MODE=PostgreSQL
    driverClassName: org.h2.Driver
    username: some_login
    password: some_password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  flyway:
    enabled: true
    locations: classpath:db/migration
